/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfUseRouteImport } from './routes/terms-of-use'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsIdRouteImport } from './routes/locations.$id'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedAdminRouteImport } from './routes/_authed.admin'
import { Route as AuthedAdminIndexRouteImport } from './routes/_authed.admin.index'
import { Route as AuthedBookIdRouteImport } from './routes/_authed.book.$id'
import { Route as AuthedAdminQuotesRouteImport } from './routes/_authed.admin.quotes'
import { Route as AuthedAdminBookingsRouteImport } from './routes/_authed.admin.bookings'
import { Route as AuthedAdminBillboardsRouteImport } from './routes/_authed.admin.billboards'
import { Route as AuthedAdminBillboardsIndexRouteImport } from './routes/_authed.admin.billboards.index'
import { Route as AuthedAdminBillboardsNewRouteImport } from './routes/_authed.admin.billboards.new'
import { Route as AuthedAdminBillboardsIdRouteImport } from './routes/_authed.admin.billboards.$id'

const TermsOfUseRoute = TermsOfUseRouteImport.update({
  id: '/terms-of-use',
  path: '/terms-of-use',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIdRoute = LocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminIndexRoute = AuthedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedBookIdRoute = AuthedBookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminQuotesRoute = AuthedAdminQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminBookingsRoute = AuthedAdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminBillboardsRoute = AuthedAdminBillboardsRouteImport.update({
  id: '/billboards',
  path: '/billboards',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminBillboardsIndexRoute =
  AuthedAdminBillboardsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedAdminBillboardsRoute,
  } as any)
const AuthedAdminBillboardsNewRoute =
  AuthedAdminBillboardsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthedAdminBillboardsRoute,
  } as any)
const AuthedAdminBillboardsIdRoute = AuthedAdminBillboardsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedAdminBillboardsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/admin/billboards': typeof AuthedAdminBillboardsRouteWithChildren
  '/admin/bookings': typeof AuthedAdminBookingsRoute
  '/admin/quotes': typeof AuthedAdminQuotesRoute
  '/book/$id': typeof AuthedBookIdRoute
  '/admin/': typeof AuthedAdminIndexRoute
  '/admin/billboards/$id': typeof AuthedAdminBillboardsIdRoute
  '/admin/billboards/new': typeof AuthedAdminBillboardsNewRoute
  '/admin/billboards/': typeof AuthedAdminBillboardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations': typeof LocationsIndexRoute
  '/admin/bookings': typeof AuthedAdminBookingsRoute
  '/admin/quotes': typeof AuthedAdminQuotesRoute
  '/book/$id': typeof AuthedBookIdRoute
  '/admin': typeof AuthedAdminIndexRoute
  '/admin/billboards/$id': typeof AuthedAdminBillboardsIdRoute
  '/admin/billboards/new': typeof AuthedAdminBillboardsNewRoute
  '/admin/billboards': typeof AuthedAdminBillboardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/industries': typeof IndustriesRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sign-in': typeof SignInRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-use': typeof TermsOfUseRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/locations/$id': typeof LocationsIdRoute
  '/locations/': typeof LocationsIndexRoute
  '/_authed/admin/billboards': typeof AuthedAdminBillboardsRouteWithChildren
  '/_authed/admin/bookings': typeof AuthedAdminBookingsRoute
  '/_authed/admin/quotes': typeof AuthedAdminQuotesRoute
  '/_authed/book/$id': typeof AuthedBookIdRoute
  '/_authed/admin/': typeof AuthedAdminIndexRoute
  '/_authed/admin/billboards/$id': typeof AuthedAdminBillboardsIdRoute
  '/_authed/admin/billboards/new': typeof AuthedAdminBillboardsNewRoute
  '/_authed/admin/billboards/': typeof AuthedAdminBillboardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/portfolio'
    | '/privacy-policy'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/admin'
    | '/dashboard'
    | '/locations/$id'
    | '/locations/'
    | '/admin/billboards'
    | '/admin/bookings'
    | '/admin/quotes'
    | '/book/$id'
    | '/admin/'
    | '/admin/billboards/$id'
    | '/admin/billboards/new'
    | '/admin/billboards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/industries'
    | '/portfolio'
    | '/privacy-policy'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/dashboard'
    | '/locations/$id'
    | '/locations'
    | '/admin/bookings'
    | '/admin/quotes'
    | '/book/$id'
    | '/admin'
    | '/admin/billboards/$id'
    | '/admin/billboards/new'
    | '/admin/billboards'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/about'
    | '/contact'
    | '/industries'
    | '/portfolio'
    | '/privacy-policy'
    | '/sign-in'
    | '/sitemap.xml'
    | '/terms-of-use'
    | '/_authed/admin'
    | '/_authed/dashboard'
    | '/locations/$id'
    | '/locations/'
    | '/_authed/admin/billboards'
    | '/_authed/admin/bookings'
    | '/_authed/admin/quotes'
    | '/_authed/book/$id'
    | '/_authed/admin/'
    | '/_authed/admin/billboards/$id'
    | '/_authed/admin/billboards/new'
    | '/_authed/admin/billboards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  IndustriesRoute: typeof IndustriesRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SignInRoute: typeof SignInRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfUseRoute: typeof TermsOfUseRoute
  LocationsIdRoute: typeof LocationsIdRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-use': {
      id: '/terms-of-use'
      path: '/terms-of-use'
      fullPath: '/terms-of-use'
      preLoaderRoute: typeof TermsOfUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$id': {
      id: '/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof LocationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/': {
      id: '/_authed/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthedAdminIndexRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/book/$id': {
      id: '/_authed/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof AuthedBookIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/quotes': {
      id: '/_authed/admin/quotes'
      path: '/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AuthedAdminQuotesRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/bookings': {
      id: '/_authed/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthedAdminBookingsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/billboards': {
      id: '/_authed/admin/billboards'
      path: '/billboards'
      fullPath: '/admin/billboards'
      preLoaderRoute: typeof AuthedAdminBillboardsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/billboards/': {
      id: '/_authed/admin/billboards/'
      path: '/'
      fullPath: '/admin/billboards/'
      preLoaderRoute: typeof AuthedAdminBillboardsIndexRouteImport
      parentRoute: typeof AuthedAdminBillboardsRoute
    }
    '/_authed/admin/billboards/new': {
      id: '/_authed/admin/billboards/new'
      path: '/new'
      fullPath: '/admin/billboards/new'
      preLoaderRoute: typeof AuthedAdminBillboardsNewRouteImport
      parentRoute: typeof AuthedAdminBillboardsRoute
    }
    '/_authed/admin/billboards/$id': {
      id: '/_authed/admin/billboards/$id'
      path: '/$id'
      fullPath: '/admin/billboards/$id'
      preLoaderRoute: typeof AuthedAdminBillboardsIdRouteImport
      parentRoute: typeof AuthedAdminBillboardsRoute
    }
  }
}

interface AuthedAdminBillboardsRouteChildren {
  AuthedAdminBillboardsIdRoute: typeof AuthedAdminBillboardsIdRoute
  AuthedAdminBillboardsNewRoute: typeof AuthedAdminBillboardsNewRoute
  AuthedAdminBillboardsIndexRoute: typeof AuthedAdminBillboardsIndexRoute
}

const AuthedAdminBillboardsRouteChildren: AuthedAdminBillboardsRouteChildren = {
  AuthedAdminBillboardsIdRoute: AuthedAdminBillboardsIdRoute,
  AuthedAdminBillboardsNewRoute: AuthedAdminBillboardsNewRoute,
  AuthedAdminBillboardsIndexRoute: AuthedAdminBillboardsIndexRoute,
}

const AuthedAdminBillboardsRouteWithChildren =
  AuthedAdminBillboardsRoute._addFileChildren(
    AuthedAdminBillboardsRouteChildren,
  )

interface AuthedAdminRouteChildren {
  AuthedAdminBillboardsRoute: typeof AuthedAdminBillboardsRouteWithChildren
  AuthedAdminBookingsRoute: typeof AuthedAdminBookingsRoute
  AuthedAdminQuotesRoute: typeof AuthedAdminQuotesRoute
  AuthedAdminIndexRoute: typeof AuthedAdminIndexRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminBillboardsRoute: AuthedAdminBillboardsRouteWithChildren,
  AuthedAdminBookingsRoute: AuthedAdminBookingsRoute,
  AuthedAdminQuotesRoute: AuthedAdminQuotesRoute,
  AuthedAdminIndexRoute: AuthedAdminIndexRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedBookIdRoute: typeof AuthedBookIdRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedBookIdRoute: AuthedBookIdRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  IndustriesRoute: IndustriesRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SignInRoute: SignInRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfUseRoute: TermsOfUseRoute,
  LocationsIdRoute: LocationsIdRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
